### ISSUE TITLE
SIGTERM in destructor does not kill process on RHEL 7

### ISSUE THREAD

**Issue by laouji** [tokuhirom/Test-TCP#31] opened 2015-01-05 15:08 UTC
I discovered this problem while installing [Furl](https://github.com/tokuhirom/Furl) on a RHEL 7 machine using Perl 5.18.0.

```
t/100_low/22_keep_alive_http10.t ................ 1/?
Building and testing Furl-3.05 ... FAIL
! Timed out (> 1800s). Use --verbose to retry.
Terminated
```

Using the functional interface (`test_tcp()`) like Furl's [t/100_low/22_keep_alive_http10.t](https://github.com/tokuhirom/Furl/blob/master/t/100_low/22_keep_alive_http10.t) does will cause the test to hang indefinitely in the destructor:

```perl
#Test/TCP.pm

19 my $TERMSIG = $^O eq 'MSWin32' ? 'KILL' : 'TERM';

 96 sub stop {
 97     my $self = shift;
...
113         kill $TERMSIG => $self->{pid};
...
119     LOOP: while (1) {
120         my $kid = waitpid( $self->{pid}, 0 ); # does not pass this point
...
132     }
133     undef $self->{pid};
134 }
```

Modifying the `stop()` function so it uses SIGKILL instead of SIGTERM (as was done with 'MSWin32') will terminate the process... but I am not sure why the process is not responding to SIGTERM.

```perl
#Test/TCP.pm

113         kill 'KILL' => $self->{pid};
```

**Comment by tokuhirom** [comment] 2015-01-08 08:50
patches welcome

**Comment by mattn** [comment] 2015-01-08 09:00
On windows, perl emulate SIGTERM like CTRL-BREAK.

https://github.com/Perl/perl5/blob/0a9cc54c57f019e71d784ddfbc4eba91efb22770/win32/win32.c#L1239

But perl seems replacing it to SIGBREAK

https://github.com/Perl/perl5/blob/0a9cc54c57f019e71d784ddfbc4eba91efb22770/win32/win32.c#L4597

So, Well..., Perhaps, Maybe..., If it handle SIGBREAK, It maybe work.

**Comment by kazuho** [comment] 2015-04-02 03:20
@laouji @tokuhirom 
IMO we should not switch from `SIGTERM` to `SIGKILL`, since it would prevent the shutdown logic implement within the server from running.

I believe that the server being tested should be fixed instead (if it does not respond to `SIGTERM`).

**Comment by laouji** [comment] 2015-04-04 03:02
Yeah, I get the idea that using `SIGKILL` is not the right thing to do on a Unix based system, but I wasn't sure of the exact cause of the issue and have not had the time to investigate any further.

@kazuho you are probably right that the problem has something to do with the way the Starlet server is implemented in the Furl test.
In which case, this issue has been raised in the wrong repository. :bow: 

@tokuhirom You can close this issue if you feel it might be handled better somewhere else.

**Comment by kazuho** [comment] 2015-04-05 00:48
@laouji 
> you are probably right that the problem has something to do with the way the Starlet server is implemented in the Furl test.

Sorry, I hadn't recognized that the test script in question was that of Furl and the server used for the test was Starlet.  Considering the fact that the authors for both softwares are already on this issue, I think continuing the discussion here would make sense (until we find out the reason why).

@laouji Is the problem reproducible on with the latest versions of Furl and Starlet on RHEL 7?  I fail to reproduce on Ubuntu 14.04 amd64.

**Comment by laouji** [comment] 2015-04-20 06:24
It looks like Furl's minimum Test::TCP version is an older one:
`requires 'Test::TCP'  => 1.06;`

But I can reproduce the error on versions as new as `Test::TCP 2.02`.
However if I manually install `Test::TCP 2.11` the test passes. :smile: 

Upgrading the versioning info on Furl should prevent older versions of this module from being used. So this is more of a Furl issue than a Test::TCP one.

**Comment by kazuho** [comment] 2015-04-20 07:16
@laouji Glad to hear that!

@tokuhirom Would you mind updating the cpanfile of Furl so that it would require a newer version of Test::TCP?

**Comment by tokuhirom** [comment] 2015-04-21 03:44
@kazuho 
done https://github.com/tokuhirom/Furl/commit/2ff8e5e8df38aec26f5804e2d6e657aee22b1107

**Comment by kazuho** [comment] 2015-04-22 02:21
@tokuhirom :+1: Thask a lot!

**Closed by kazuho** 2015-04-22 02:21 UTC
